
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author ACER
 */

public class GameFrame extends javax.swing.JDialog {

    ArrayList<Question> questions = new ArrayList<Question>();
    private Random  rnd = new Random();
    int Level = 0;
    int sum = 500;
    int amountHints = 0;
    boolean rightMistake = false;
    Question currentQuestion;

    /**
     * Creates new form GameFrame
     */
    public GameFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dataBase();
        //ReadFile();
        startGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();
        questionAndAnswersPanel = new javax.swing.JPanel();
        lblQuestionText = new javax.swing.JLabel();
        btnAnswer1 = new javax.swing.JButton();
        btnAnswer3 = new javax.swing.JButton();
        btnAnswer2 = new javax.swing.JButton();
        btnAnswer4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLevel = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        controlPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        controlPanel.setName("controlPanel"); // NOI18N
        bntFiftyFiftyActionPerformed = new javax.swing.JButton();
        bntHelpActionPerformed = new javax.swing.JButton();
        bntCallActionPerformed = new javax.swing.JButton();
        bntRightMistakeActionPerformed = new javax.swing.JButton();
        bntChangeQuestionActionPerformed = new javax.swing.JButton();
        bntGiveMyMoneyActionPerformed = new javax.swing.JButton();
        bntFiftyFiftyActionPerformed.setText("50/50");
        bntHelpActionPerformed.setText("Помощь зала");
        bntCallActionPerformed.setText("Звонок другу");
        bntRightMistakeActionPerformed.setText("Право на ошибку");
        bntChangeQuestionActionPerformed.setText("Замена вопроса");
        bntGiveMyMoneyActionPerformed.setText("Забрать деньги");
        bntFiftyFiftyActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntFiftyFiftyActionPerformedActionPerformed(evt);
            }
        });
        bntHelpActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHelpActionPerformedActionPerformed(evt);
            }
        });
        bntCallActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCallActionPerformedActionPerformed(evt);
            }
        });
        bntRightMistakeActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRightMistakeActionPerformedActionPerformed(evt);
            }
        });
        bntChangeQuestionActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntChangeQuestionActionPerformedActionPerformed(evt);
            }
        });
        bntGiveMyMoneyActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGiveMyMoneyActionPerformedActionPerformed(evt);
            }
        });
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\IdeaProjects\\For_Learn\\src\\picture.jpg")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        questionAndAnswersPanel.setName("questionAndAnswersPanel"); // NOI18N

        btnAnswer1.setText("btnAnswer1");
        btnAnswer1.setActionCommand("1");
        btnAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer1ActionPerformed(evt);
            }
        });

        btnAnswer3.setText("btnAnswer3");
        btnAnswer3.setActionCommand("3");
        btnAnswer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer3ActionPerformed(evt);
            }
        });

        btnAnswer2.setText("btnAnswer2");
        btnAnswer2.setActionCommand("2");
        btnAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer2ActionPerformed(evt);
            }
        });

        btnAnswer4.setText("btnAnswer4");
        btnAnswer4.setActionCommand("4");
        btnAnswer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer4ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(controlPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bntFiftyFiftyActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntFiftyFiftyActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntHelpActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntCallActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntRightMistakeActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntChangeQuestionActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(controlPanelLayout.createSequentialGroup()
                                                .addComponent(bntGiveMyMoneyActionPerformed)
                                                .addGap(0, 1, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(bntFiftyFiftyActionPerformed)
                                //.addGap(18, 18, 18)
                                .addComponent(bntHelpActionPerformed)
                                //.addGap(18, 18, 18)
                                .addComponent(bntCallActionPerformed)
                               // .addGap(18, 18, 18)
                                .addComponent(bntRightMistakeActionPerformed)
                                //.addGap(18, 18, 18)
                                .addComponent(bntChangeQuestionActionPerformed)
                                //.addGap(18, 18, 1
                                .addContainerGap(80, Short.MAX_VALUE)
                                .addComponent(bntGiveMyMoneyActionPerformed)

                                )
        );

        javax.swing.GroupLayout questionAndAnswersPanelLayout = new javax.swing.GroupLayout(questionAndAnswersPanel);
        questionAndAnswersPanel.setLayout(questionAndAnswersPanelLayout);
        questionAndAnswersPanelLayout.setHorizontalGroup(
                questionAndAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionAndAnswersPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblQuestionText)
                                .addGap(291, 291, 291))
                        .addGroup(questionAndAnswersPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(questionAndAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(questionAndAnswersPanelLayout.createSequentialGroup()
                                                .addComponent(btnAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(questionAndAnswersPanelLayout.createSequentialGroup()
                                                .addComponent(btnAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        questionAndAnswersPanelLayout.setVerticalGroup(
                questionAndAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(questionAndAnswersPanelLayout.createSequentialGroup()
                                .addComponent(lblQuestionText)
                                .addGap(44, 44, 44)
                                .addGroup(questionAndAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAnswer1)
                                        .addComponent(btnAnswer3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(questionAndAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAnswer2)
                                        .addComponent(btnAnswer4))
                                .addGap(0, 37, Short.MAX_VALUE))
        );

        lstLevel.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "3 000 000", "1 500 000", "   800 000", "   400 000", "   200 000", "   100 000", "     50 000", "     25 000", "     15 000", "     10 000", "       5 000", "       3 000", "       2 000", "       1 000", "          500" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLevel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(questionAndAnswersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(26, 26, 26))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(questionAndAnswersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void btnAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (currentQuestion.RightAnswer.equals(evt.getActionCommand())) {
            rightMistake = false;
            NextStep();
        }
        else
        {
            answerToTheQuestion(evt);
        }
    }

    private void btnAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (currentQuestion.RightAnswer.equals(evt.getActionCommand())) {
            rightMistake = false;
            NextStep();
        }
        else
        {
            answerToTheQuestion(evt);
        }
    }

    private void btnAnswer3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (currentQuestion.RightAnswer.equals(evt.getActionCommand())) {
            rightMistake = false;
            NextStep();
        }
        else
        {
            answerToTheQuestion(evt);
        }
    }

    private void btnAnswer4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (currentQuestion.RightAnswer.equals(evt.getActionCommand())) {
            NextStep();
            rightMistake = false;
        }
        else
        {
            answerToTheQuestion(evt);
        }
    }

    private void bntFiftyFiftyActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(amountHints < 4) {
            JButton[] btns = new JButton[]{btnAnswer1, btnAnswer2, btnAnswer3, btnAnswer4};

            int count = 0;
            while (count < 2) {
                int n = rnd.nextInt(4);
                String ac = btns[n].getActionCommand();

                if (!ac.equals(currentQuestion.RightAnswer)
                        && btns[n].isEnabled()) {
                    btns[n].setEnabled(false);
                    count++;
                }
            }
            bntFiftyFiftyActionPerformed.setEnabled(false);
            amountHints++;
        }
        else
        {
            Notification();
        }
    }
    private void bntHelpActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {
        if(amountHints < 4) {
            JButton[] btns = new JButton[]{btnAnswer1, btnAnswer2, btnAnswer3, btnAnswer4};
            int[] probabilities = new int[]{0,0,0,0};
            int correct = -1;
            int difference = 0;
            Random random = new Random();
            for (int i = 0; i < 4; i++) {
                String ac = btns[i].getActionCommand();
                if (ac.equals(currentQuestion.RightAnswer)) {
                    probabilities[i] = random.nextInt(60)+45;
                    correct = i;
                }
            }
            for(int i = 0; i < 4; i++)
            {
                if(i != correct)
                {
                    difference = 100-probabilities[1]-probabilities[2]-probabilities[3]-probabilities[0];
                    if(difference > 0)
                        probabilities[i] = random.nextInt(difference);
                }
            }
            int i = random.nextInt(4);
            probabilities[i] = 100-probabilities[1]-probabilities[2]-probabilities[3]-probabilities[0];
            JOptionPane.showMessageDialog(this, "1: " + Integer.toString(probabilities[0]) + "%" + "\n2: " + Integer.toString(probabilities[1]) + "%" + "\n3: " + Integer.toString(probabilities[2]) + "%" + "\n4: " + Integer.toString(probabilities[3]) + "%", "Помощь зала", 1);

            bntHelpActionPerformed.setEnabled(false);
            amountHints++;
        }
        else
        {
            Notification();
        }
    }
    private void bntCallActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {

        if(amountHints < 4) {
            JButton[] btns = new JButton[]{btnAnswer1, btnAnswer2, btnAnswer3, btnAnswer4};
            Random random = new Random();
            int rand = random.nextInt(10) + 1; //от 1 до 10
            if (rand != 10) { //если не выпало 10, то друг говорит случайный ответ
                for (int i = 0; i < 4; i++) {
                    String ac = btns[i].getActionCommand();

                    if (ac.equals(currentQuestion.RightAnswer)) {
                        JOptionPane.showMessageDialog(this, "Я думаю, что правильный ответ " + Integer.toString(i + 1), "Друг", 1);
                        break;
                    }
                }
                bntCallActionPerformed.setEnabled(false);
                amountHints++;
            }
            else
            {
                rand = random.nextInt(4) + 1;
                JOptionPane.showMessageDialog(this, "Я думаю, что правильный ответ " + Integer.toString(rand), "Друг", 1);
            }
        }
        else
        {
            Notification();
        }
    }
    private void bntRightMistakeActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {
        if(amountHints < 4) {
            rightMistake = true;
            bntRightMistakeActionPerformed.setEnabled(false);
            amountHints++;
        }
        else
        {
            Notification();
        }
    }
    private void bntChangeQuestionActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {
        if(amountHints < 4) {
            currentQuestion = GetQuestion(Level);
            ShowQuestion(currentQuestion);
            lstLevel.setSelectedIndex(lstLevel.getModel().getSize()-Level);
            bntChangeQuestionActionPerformed.setEnabled(false);
            amountHints++;
        }
        else
        {
            Notification();
        }
    }
    private void bntGiveMyMoneyActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {
        if(amountHints < 4) {

            if(Level != 1) {
                JOptionPane.showMessageDialog(this, "Поздравляем, Ваш выигрыш составил " + lstLevel.getModel().getElementAt(15 - Level) + " рублей!");
                bntGiveMyMoneyActionPerformed.setEnabled(false);
                amountHints++;
                startGame();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Вам нужно ответить хотя-бы на один вопрос.", "Уведомление", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        else
        {
            Notification();
        }
    }
    private void Notification()
    {
        JOptionPane.showMessageDialog(null,
                "Ты использовал все подсказки",
                "Уведомление",
                JOptionPane.INFORMATION_MESSAGE);
    }
    private void dataBase()
    {
        try{
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\Users\\ACER\\Desktop\\labJava\\questions.db");

            Statement statmt = conn.createStatement();
            //String query = "select name, answer1, answer2, answer3, answer4, rightAnswer, level" +
                   // "	from questions";
            String query = "select *" + "	from questions";

            ResultSet resSet = statmt.executeQuery(query);

            while (resSet.next()) {
                String[] s = new String[]{resSet.getString(1), resSet.getString(2), resSet.getString(3), resSet.getString(4), resSet.getString(5), resSet.getString(6), resSet.getString(7)};
                questions.add(new Question(s));
            }

            resSet.close();
            conn.close();

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }
    private void ReadFile()
    {
        try{
            FileInputStream fstream = new FileInputStream("C:\\Users\\ACER\\IdeaProjects\\For_Learn\\src\\Вопросы.txt");
            //BufferedReader br = new BufferedReader(new InputStreamReader(fstream, "Cp1251"));
            BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
            String strLine;
            while ((strLine = br.readLine()) != null) {
                String[] s = strLine.split("\t");
                questions.add(new Question(s));
            }
        } catch (IOException e) {
            System.out.println("Ошибка!!!!!!!!");
        }
    }
    private void ShowQuestion(Question q)
    {
        lblQuestionText.setText(q.Text);
        btnAnswer1.setText(q.Answers[0]);
        btnAnswer2.setText(q.Answers[1]);
        btnAnswer3.setText(q.Answers[2]);
        btnAnswer4.setText(q.Answers[3]);
    }
    private Question GetQuestion(int level)
    {
        List<Question> list = questions.stream().filter(q->q.Level==level).collect(Collectors.toList());
        return list.get(rnd.nextInt(list.size()));
    }
    private void NextStep()
    {
        JButton[] btns = new JButton[]{btnAnswer1, btnAnswer2, btnAnswer3, btnAnswer4};

        for(JButton btn: btns)
            btn.setEnabled(true);
        if (Level<15) {
            Level++;
            currentQuestion = GetQuestion(Level);
            ShowQuestion(currentQuestion);
            lstLevel.setSelectedIndex(lstLevel.getModel().getSize() - Level);
        }
        else{
            JOptionPane.showMessageDialog(this, "Вы выиграли игру!\nВаш выигрыш составил 3 000 000 рублей!!!");
            startGame();
        }
    }
    private void startGame()
    {
        bntFiftyFiftyActionPerformed.setEnabled(true);
        bntHelpActionPerformed.setEnabled(true);
        bntCallActionPerformed.setEnabled(true);
        bntRightMistakeActionPerformed.setEnabled(true);
        bntChangeQuestionActionPerformed.setEnabled(true);
        bntGiveMyMoneyActionPerformed.setEnabled(true);
        bntGiveMyMoneyActionPerformed.setEnabled(true);
        String[] strings = { "3000000", "1500000", "800000", "400000", "200000", "100000", "50000", "25000", "15000", "10000", "5000", "3000", "2000", "1000", "500" };

        String dev = (String)JOptionPane.showInputDialog(null,"Выберите несгораемую сумму","Несгораемая сумма",JOptionPane.PLAIN_MESSAGE,null,strings,null);
        sum = Integer.parseInt(dev);
        amountHints = 0;
        Level = 0;
        rightMistake = false;
        NextStep();
    }

    private void answerToTheQuestion(java.awt.event.ActionEvent evt)
    {
        if(rightMistake)
        {
            JOptionPane.showMessageDialog(this, "Вы ответили неверно, но у Вас есть еще одна попытка!");
            rightMistake = false;
        }
        else if (Level > incombustibleLevel())
        {
            JOptionPane.showMessageDialog(this, "Ответ неверный, но Вы получаете несгораемую сумму: " + lstLevel.getModel().getElementAt(15-incombustibleLevel()) + " рублей!");
            startGame();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Ответ неверный, Вы проиграли.");
            startGame();
        }
    }
    private int incombustibleLevel()
    {
        int level = 0;
        for (int i=0; i < lstLevel.getModel().getSize(); i++)
        {
            String s = lstLevel.getModel().getElementAt(i).replaceAll(" ", "");
            if (sum == Integer.parseInt(s))
            {
                level = 15 - i;
                break;
            }
        }
        return level;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame

.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame

.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame

.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame

.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            GameFrame

 dialog = new GameFrame

(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });

    }


    // Variables declaration - do not modify
    private javax.swing.JButton bntFiftyFiftyActionPerformed;
    private javax.swing.JButton btnAnswer1;
    private javax.swing.JButton btnAnswer2;
    private javax.swing.JButton btnAnswer3;
    private javax.swing.JButton btnAnswer4;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuestionText;
    private javax.swing.JList<String> lstLevel;
    private javax.swing.JPanel questionAndAnswersPanel;
    private JPanel panel1;
    private JButton bntHelpActionPerformed;
    private JButton bntCallActionPerformed;
    private JButton bntRightMistakeActionPerformed;
    private JButton bntChangeQuestionActionPerformed;
    private JButton bntGiveMyMoneyActionPerformed;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
    // End of variables declaration
}
